# syntax=docker/dockerfile:1

FROM python:3.8.10
COPY requirements.txt opt/
RUN pip install lxml
RUN pip install -r opt/requirements.txt
COPY build/ /src/app/train_model/
WORKDIR /src/app/train_model/
CMD ["python3", "train_model.py"]