version: '3'
services:

  users_insertion:
    hostname: users_insertion
    build:
      context: .
      dockerfile: dockerfile
    container_name: users_insertion
    volumes:
      - ./data/:/src/app/consumption_app/data
      - ./config/:/src/app/consumption_app/config
      - ./logs/:/src/app/consumption_app/logs
    networks:
      - smi_net

networks:
  smi_net:
    driver: bridge
    external: true