# syntax=docker/dockerfile:1

FROM python:3.8.10
COPY requirements.txt home/app/users_insertion/
RUN pip install lxml
RUN pip install -r home/app/users_insertion/requirements.txt
COPY build/ /home/app/users_insertion/
WORKDIR /home/app/users_insertion/
CMD ["python3", "get_users.py"]