# syntax=docker/dockerfile:1

FROM python:3.8.10
COPY requirements.txt opt/
RUN pip install lxml
RUN pip install -r opt/requirements.txt
COPY build/ /src/app/db_creation/
WORKDIR /src/app/db_creation/
CMD ["python3", "main.py"]